# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6b98f7f1202a8dba89bbf9ecabc5d65525a0767247715e3b558146c539b9d0f9ddce98e4637097c61c96621421602348246d85f8c51f58ac5a09c13829200be

test:
  secret_key_base: ca1fbbba44791c4340be1b181df3f17ac34dbd0f5f2c07acf2214d0fabddd7d537f0abfa72fe64edcfe9230789393e0acb84c4349ac829b8dc4507c22e5de353

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
